# Autogenerated wrapper script for ImarisWriter_jll for x86_64-w64-mingw32-cxx03
export libbpImarisWriter96

using HDF5_jll
using Lz4_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ImarisWriter")
JLLWrappers.@declare_library_product(libbpImarisWriter96, "libbpImarisWriter96.dll")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, Lz4_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libbpImarisWriter96,
        "bin\\libbpImarisWriter96.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
